version: 2
jobs:
  build:
    working_directory: ~/npm-lib
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn
      - run:
          name: Code Climate reporter
          command: yarn add global codeclimate-test-reporter
      - save_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
            - ~/.config/yarn/global
  test:
    working_directory: ~/npm-lib
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json" }}
      - run:
          name: Test using yarn
          command: yarn test | tap-xunit > ava.xml
      - run:
          name: Run coverage report
          command: yarn run converage > coverage-report
      - run:
          name: Send code climate test coverage
          command: CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage-report
      - store_test_results:
          path: ava.xml
      - store_artifacts:
          path: ava.xml
          prefix: reports
      - store_artifacts:
          path: converage-report
          prefix: reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
