# .circleci/config.yml
defaults: &defaults
  working_directory: ~/npm-lib
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn
      - run:
          name: Code Climate reporter
          command: yarn global add codeclimate-test-reporter
      - save_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules
            - ~/.config/yarn/global
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ arch }}-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Test using yarn
          command: yarn test | npx tap-xunit > ava.xml
      - run:
          name: Run coverage report
          command: |
            ./cc-test-reporter before-build
            yarn run coverage > coverage-report.lcov
            ./cc-test-reporter after-build -d --coverage-input-type lcov --exit-code $?
      - store_artifacts:
          path: ava.xml
          prefix: reports
      - store_artifacts:
          path: converage-report
          prefix: reports
      - store_test_results:
          path: ava.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
